### ISSUE TITLE
Show date of when a specific file has been updated on dendron.so at the top of each page.

### ISSUE THREAD

**Issue by agichim** [dendronhq/dendron-site#21]
It will make searching through the docs for new information easier. Currently, I have to review docs that I've already read just to make sure that something hasn't been added.

**Comment by kevinslin** [comment]
we currently have a `last modified` date at the bottom of each page. to be clear, you would like this to be moved to the top or be more prominent in the page?

**Comment by agichim** [comment]
The last modified at the bottom of the page is what I meant. I don't recall that being there when I posted the issue, it must be a new implementation :)

**Comment by agichim** [comment]
Does the `last modified` show by default in the latest version of Dendron or do I need to add it somewhere?

**Comment by kevinslin** [comment]
It's a new option:
https://wiki.dendron.so/notes/f2ed8639-a604-4a9d-b76c-41e205fb8713.html#sitelastmodified-optional
:)

**Comment by kpathakota** [comment]
Closing out issue - hope it's all good @agichim
