### ISSUE TITLE
Inconsistent capitalization

### ISSUE THREAD

**Issue by jimt** [dendronhq/dendron-site#333]
A small quibble, but reading through the guide, I believe there is inconsistent capitalization of some proper nouns:

dendron/**Dendron**
vscode/VSCode/**VS Code** (see https://code.visualstudio.com/)
markdown/**Markdown** ([example usage](https://docs.github.com/en/github/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#quoting-code))
vim/**Vim**
emacs/**Emacs**
sublime/**Sublime** (or canonically **Sublime Text**)

**Comment by cconrad** [comment]
Funny, this is also a quibble for me and I started working on aligning the different capitalizations of VS Code (which is currently spelled VSCode, VsCode, Vscode, vscode and VSC) around the same time that you reported this issue. I'll open a pull request for this soon.

**Comment by cconrad** [comment]
Note to self:
Add "jekyll/Jekyll" to the list of proper nouns

**Comment by ScriptAutomate** [comment]
I'm thinking of making a basic style guide, and would like to evaluate something like [Vale]() as a way to catch standardized casing, etc. (such as `vscode` vs. `VS Code` and others mentioned in this issue).
