### ISSUE TITLE
Troubleshooting #lookup-shortcut-is-not-working?

### ISSUE THREAD

**Issue by henry-js** [dendronhq/dendron-site#357]
I think [\#lookup-shortcut-is-not-working](https://wiki.dendron.so/notes/a6c03f9b-8959-4d67-8394-4d204ab69bfe/#lookup-shortcut-is-not-working) is missing a keybinding override.

There are two <CTRL+L> keybindings that conflict with the dendron lookup command. [One is built in](https://code.visualstudio.com/docs/getstarted/keybindings#_when-clause-contexts) and the other is installed with VSCodeVim.
I have no idea what the VSCodeVim shortcut does but have asked [here](https://github.com/VSCodeVim/Vim/discussions/7390).

**Comment by ScriptAutomate** [comment]
Good point, looks like the VS Code docs say:

Command | Key | Command id
-- | -- | --
Select all occurrences of current selection | `Ctrl+Shift+L` | `editor.action.selectHighlights`
Select current line | `Ctrl+L` | `expandLineSelection`

And the Dendron docs say, when it comes to a conflict with `Ctrl+L` for lookup:

```
    causes:
        you have the Vim extension installed and it's overriding the default Dendron shortcut
    fix:
        open command palette and run Open Keyboard Shortcuts (JSON)
        add the following shortcut override
        NOTE: replace cmd+l with ctrl+l if you are on windows
```
```json
    {
      "key": "cmd+l",
      "command": "-expandLineSelection",
      "when": "textInputFocus"
    }
```
`expandLineSelection` looks to be a built-in VS Code command. I'm not sure what the `vim` extension must be doing here (I don't personally use the extension).

- Does this mean that, when you follow the directions in the Dendron docs, Lookup still fails to work with `Ctrl+L`/`Cmd+L`?

**Comment by henry-js** [comment]
Yeah, I also had to add
```json
    {
        "key": "ctrl+l",
        "command": "-extension.vim_navigateCtrlL",
        "when": "editorTextFocus && vim.active && vim.use<C-l> && !inDebugRepl"
    }
```
to get mine to work. The VSCodeVim authors haven't got back to me yet on what their command is supposed to do

**Comment by ScriptAutomate** [comment]
Thanks for figuring this out! I have added your workaround to our docs:
- https://github.com/dendronhq/dendron-site/commit/a4765bcea4a99f73267f6cdfc40a97d00d065433

This will be live on the published site when we do the next iteration of docs release on Friday. I'll be closing this issue as resolved.
