### ISSUE TITLE
Updates to the Extensions page on the Dendron Wiki

### ISSUE THREAD

**Issue by micharris42** [dendronhq/dendron-site#359]
The [Extensions page](https://wiki.dendron.so/notes/301e4129-6933-4be7-a4bd-8125171360d8/) on the Dendron Wiki should be updated.

The [Dendron Snippet Maker](https://marketplace.visualstudio.com/items?itemName=dendron.dendron-snippet-maker) extension is currently not included at all, either under "Bundled" or "Archived / Deprecated". As it is not bundled with Dendron, it is most likely deprecated and should be added underneath the latter heading. The [Tag Search](https://marketplace.visualstudio.com/items?itemName=d3vr.tag-search) extension most likely falls under the same category.

Additionally, the content of "Other VS Code Extensions" is not displayed properly. The section only contains the error message: "Start anchor other-vscode-extensions not found". 

Lastly, while the "Other VS Code Extensions" links to the [Tips page](https://wiki.dendron.so/notes/692fa114-f798-467f-a0b9-3cccc327aa6f/), there are other recommended extensions scattered throughout the wiki. For example, the [Markdown page](https://wiki.dendron.so/notes/ba97866b-889f-4ac6-86e7-bb2d97f6e376/) recommends the [Text Tables](https://marketplace.visualstudio.com/items?itemName=RomanPeshkov.vscode-text-tables) extension. These extensions should also be aggregated on the Extensions page.

Thank you.

**Comment by SeriousBug** [comment]
I believe @ScriptAutomate has fixes/is fixing some of these issues already, but I'll tag him as a reminder.

**Comment by ScriptAutomate** [comment]
> The [Dendron Snippet Maker](https://marketplace.visualstudio.com/items?itemName=dendron.dendron-snippet-maker) extension is currently not included at all, either under "Bundled" or "Archived / Deprecated". As it is not bundled with Dendron, it is most likely deprecated and should be added underneath the latter heading.

Fixed, will be in published to public docs at end of week: https://github.com/dendronhq/dendron-site/commit/42ab9d6a0f356076d84a8af56b86698d893237c7

> The [Tag Search](https://marketplace.visualstudio.com/items?itemName=d3vr.tag-search) extension most likely falls under the same category.

I was wondering where this came from, as it isn't [officially published by Dendron](https://marketplace.visualstudio.com/publishers/dendron). It looks like _Tag Search_ appears in one place in our docs as a mention from a community member contribution:
- [changelog.release.2020-09-06](https://wiki.dendron.so/notes/08b2e6ea-bd3e-4f4b-b2b9-676a7b743a65/)
- Source repo: https://github.com/d3vr/tag-search
- Since Dendron isn't the maintainer, and it hasn't been maintained since it was originally published in 2020, I'm opting to not mention it

> Additionally, the content of "Other VS Code Extensions" is not displayed properly. The section only contains the error message: "Start anchor other-vscode-extensions not found".

Fixed, will be in published to public docs at end of week: https://github.com/dendronhq/dendron-site/commit/e245969f3b13a4ca00db475f0d1062edeaaf2777

> Lastly, while the "Other VS Code Extensions" links to the [Tips page](https://wiki.dendron.so/notes/692fa114-f798-467f-a0b9-3cccc327aa6f/), there are other recommended extensions scattered throughout the wiki. For example, the [Markdown page](https://wiki.dendron.so/notes/ba97866b-889f-4ac6-86e7-bb2d97f6e376/) recommends the [Text Tables](https://marketplace.visualstudio.com/items?itemName=RomanPeshkov.vscode-text-tables) extension. These extensions should also be aggregated on the Extensions page.

A broader discussion around this is taking place here, where that extension (along with others) are being collected. We'd love for you to join the conversation there!

- https://github.com/dendronhq/dendron/discussions/2118

Filtering with:

```bash
grep -irn 'https://marketplace.visualstudio.com' vault/*.md | 
  sed 's:.*\https:https:g' | 
  tr -d ')>:' | sed 's:\ .*::g' | 
  sed 's:\&utm.*::g' | 
  grep -v license | 
  sort | 
  uniq 
```

I get:
```
https//marketplace.visualstudio.com/items?itemName=aaronpowell.vscode-profile-switcher
https//marketplace.visualstudio.com/items?itemName=adamwalzer.string-converter
https//marketplace.visualstudio.com/items?itemName=alefragnani.Bookmarks
https//marketplace.visualstudio.com/items?itemName=ban.spellright
https//marketplace.visualstudio.com/items?itemName=CodeStream.codestream.
https//marketplace.visualstudio.com/items?itemName=cyberbiont.vscode-open-in-typora
https//marketplace.visualstudio.com/items?itemName=d3vr.tag-search
https//marketplace.visualstudio.com/items?itemName=dendron.dendron-markdown-links
https//marketplace.visualstudio.com/items?itemName=dendron.dendron-markdown-preview-enhanced
https//marketplace.visualstudio.com/items?itemName=dendron.dendron-markdown-shortcuts
https//marketplace.visualstudio.com/items?itemName=dendron.dendron-snippet-maker
https//marketplace.visualstudio.com/items?itemName=eamodio.gitlens
https//marketplace.visualstudio.com/items?itemName=equinusocio.vsc-material-theme
https//marketplace.visualstudio.com/items?itemName=formulahendry.code-runner
https//marketplace.visualstudio.com/items?itemName=frenya.vscode-recall
https//marketplace.visualstudio.com/items?itemName=geddski.macros
https//marketplace.visualstudio.com/items?itemName=generik.vertical-limit
https//marketplace.visualstudio.com/items?itemname=github.github-vscode-theme
https//marketplace.visualstudio.com/items?itemName=GitHub.vscode-pull-request-github
https//marketplace.visualstudio.com/items?itemName=Gruntfuggly.todo-tree
https//marketplace.visualstudio.com/items?itemName=ivangabriele.vscode-git-add-and-commit
https//marketplace.visualstudio.com/items?itemName=jasew.anki
https//marketplace.visualstudio.com/items?itemName=kortina.vscode-markdown-notes
https//marketplace.visualstudio.com/items?itemName=mblode.zotero
https//marketplace.visualstudio.com/items?itemName=mdickin.markdown-shortcuts
https//marketplace.visualstudio.com/items?itemName=mushan.vscode-paste-image
https//marketplace.visualstudio.com/items?itemName=notZaki.pandocciter
https//marketplace.visualstudio.com/items?itemName=orepor.color-tabs-vscode-ext
https//marketplace.visualstudio.com/items?itemName=PKief.markdown-checkbox
https//marketplace.visualstudio.com/items?itemName=ria.elastic
https//marketplace.visualstudio.com/items?itemName=RomanPeshkov.vscode-text-tables
https//marketplace.visualstudio.com/items?itemName=rxliuli.joplin-vscode-plugin
https//marketplace.visualstudio.com/items?itemName=ryanraposo.codeui
https//marketplace.visualstudio.com/items?itemName=shd101wyy.markdown-preview-enhanced
https//marketplace.visualstudio.com/items?itemName=Stalinbalraj.timestamp-converter
https//marketplace.visualstudio.com/items?itemName=svsool.markdown-kit
https//marketplace.visualstudio.com/items?itemName=tootone.org-mode
https//marketplace.visualstudio.com/items?itemName=vscodevim.vim
https//marketplace.visualstudio.com/items?itemName=vsls-contrib.gitdoc
https//marketplace.visualstudio.com/items?itemName=zeitnergmbh.auto-git
```

I'll set these up for review in the discussion.
