### ISSUE TITLE
Error guide of creating special note shortcuts

### ISSUE THREAD

**Issue by zhanghanduo** [dendronhq/dendron-site#42]
typo in "topic/lookup/creating notes":

> 
   ```
   journal: create a journal note (cmd/ctrl + shift + s)
   scratch: create a scratch note (cmd/ctrl + shift + j)
   ```

**Comment by kevinslin** [comment]
i think i'm still missing it. where is the typo? 😅

**Comment by zhanghanduo** [comment]
OK. That's weird. I found the md in [vault](https://github.com/dendronhq/dendron-site/blob/master/vault/dendron.topic.lookup.md) there is no such typo.

But if you check [https://github.com/dendronhq/dendron-site/blob/master/docs/notes/a7c3a810-28c8-4b47-96a6-8156b1524af3.md](https://github.com/dendronhq/dendron-site/blob/master/docs/notes/a7c3a810-28c8-4b47-96a6-8156b1524af3.md), you will find this typo.

**Comment by Orcomp** [comment]
@zhanghanduo Can you still see the typo? It looks good on my browser.

**Comment by kevinslin** [comment]
Closing since this should be fixed
