### ISSUE TITLE
Broken link on the features page

### ISSUE THREAD

**Issue by JekRock** [dendronhq/dendron-site#56]
There is a broken link at the https://github.com/dendronhq/dendron-site/blob/master/vault/dendron.features.md
>You can read this blog post for the extended rationale behind this.

`this blog post` leads to https://kevinslin.com/organizing/its_not_you_its_your_knowledge_base/ which returns an XML with a message `The specified key does not exist`

**Comment by Orcomp** [comment]
Double checked and was already fixed.

@kevinslin This issue can be closed.
