### ISSUE TITLE
Extra quotes in links tutorial

### ISSUE THREAD

**Issue by jeffbarr** [dendronhq/dendron-site#86]
Line 12 of the links page ( https://github.com/dendronhq/dendron-site/edit/master/vault/dendron.tutorial.links.md ) has two consecutive back-quotes before the [[  that do not appear to be necessary. I am not sufficiently confident of this to submit a PR, however.

**Comment by kpathakota** [comment]
@jeffbarr - is that line 12 of the linked MD file (or has your feedback already been fixed)(?  I see something like what you're talking about on line 20-22 but it makes sense to me: 
```
Read up on `[[`
```
Let me know and will address it asap.

**Comment by kpathakota** [comment]
Closing stale issue.
